### ISSUE TITLE
avoid deleting all files

### ISSUE THREAD

**Issue by MrFiregore** [tiersept/figma-export-colors#1]
to test the script I put in this configuration and it deleted all the files of the project

{
  "figmaPersonalToken": "xxxxxxxx",
  "fileId": "xxxxxxxxxx",
  "page": "Colors",
  "frame": "Colors",
  "exportPath": "./",
  "typescript": true
}

**Comment by tiersept** [comment]
@MrFiregore I've fixed it so it only deletes the file that it creates before creating the new one.

**Comment by MrFiregore** [comment]
that is not a good solution, the ideal would be to overwrite it if it exists.
